# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dreamreal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCGIP', models.CharField(max_length=50)),
                ('SNMP2', models.CharField(max_length=50)),
                ('SNMP3', models.CharField(max_length=50)),
                ('scg_Ap', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'SCG_Config_Devices',
            },
        ),
    ]
