# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mithun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dreamreal',
            old_name='SCGIP',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='dreamreal',
            old_name='SNMP2',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dreamreal',
            old_name='SNMP3',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='dreamreal',
            name='scg_Ap',
        ),
        migrations.AddField(
            model_name='dreamreal',
            name='phonenumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='dreamreal',
            table='dreamreal',
        ),
    ]
